---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency-analysis
  namespace: default
spec:
  args:
    - name: service-name
      value: python-app-service
  metrics:
    - name: avg-processing-time
      interval: 30s
      count: 3
      failureLimit: 1
      successCondition: result < 1.5
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
          query: |
            avg(rate(app_processing_seconds_sum{endpoint="/"}[2m])) 
            / 
            avg(rate(app_processing_seconds_count{endpoint="/"}[2m]))

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: python-app
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: python-app
          image: tonanuvem/python-app-gitops:v1
          ports:
            - containerPort: 5000
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: latency-analysis
            args:
              - name: service-name
                value: python-app-service
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
