apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: default
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
