apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: prometheus  # deve coincidir com o release do Helm
spec:
  selector:
    matchLabels:
      app: python-app
  namespaceSelector:
    matchNames:
      - default  # namespace onde está o Service
  endpoints:
    - port: http  # <-- usar o NOME da porta, como string
      path: /metrics
      interval: 15s
      scheme: http
