apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: prometheus  # Muito importante: deve corresponder ao release do Helm
spec:
  selector:
    matchLabels:
      app: python-app
  namespaceSelector:
    matchNames:
      - default  # Ou onde estiver o Service
  endpoints:
    - port: 5000
      path: /metrics
      interval: 15s
      scheme: http
